### ISSUE TITLE
Image with undefined "src" attribute

### ISSUE THREAD

**Issue by babolivier** [RobyRemzy/cozy-map#17]
cf screen capture
![capture d ecran de 2016-05-27 22-58-59](https://cloud.githubusercontent.com/assets/5547783/15621102/dbc69f12-245e-11e6-8720-a8309493e38b.png)

**Comment by jojorb** [comment]
fixed with [5d9566c ](https://github.com/RobyRemzy/cozy-map/commit/4c22f963906a0758130c94f9a779cfe1e52ef130#diff-bd9c9dcd314f2d7df52935b3a6a4d504R199)
