### ISSUE TITLE
Allow new lines in contacts addresses

### ISSUE THREAD

**Issue by nicofrand** [RobyRemzy/cozy-map#19]
Hi,

some of my contacts in my Cozy Contacts app have an address than spans on several lines.

Example:

```
25 bis rue des machins
35000 Rennes
```

When I import my contacts into cozy-map, the address becomes `25 bis rue des machins35000 Rennes` without the new line, and therefore, can't be marked on the map.

May I suggest to replace all the new lines by a simple whitespace ?

**Comment by jojorb** [comment]
sure it should be handle, i keep that post open until i find the way it should be done,
thanks @nicofrand

**Comment by jojorb** [comment]
Figure it out with the help of @frankrousseau thanks.
should be fix into next release with [commit 45348bc](https://github.com/RobyRemzy/cozy-map/commit/45348bcd9e0c1f9e6c7a319c995c436fa6662960) 
_waiting next npm package to be ready and some user test to close the issue_
