### ISSUE TITLE
Edit custom maps with markers

### ISSUE THREAD

**Issue by Phyks** [RobyRemzy/cozy-map#22]
Hi,

It would be really cool to have the ability to edit custom maps, and eventually share them, as [uMap](https://github.com/umap-project/umap/) does (software behind framacarte).

Not sure if this is an already planned feature though :)

**Comment by jojorb** [comment]
Thanks for your comment @Phyks 
Actually the only way to "edit" custom maps for now is with a MapBox account (if you have one).
- just edit your map with [MapBox Studio](https://www.mapbox.com/mapbox-studio/)
- get the raster tiles address
- copy/past it into the `New Base Layers Address` input

You can customize create makers/data/layouts to the fonts and everything... 

MAP is a Client side App so for now you cannot save you preferences or layouts permanently. 

> If this is for few makers, POI maybe consider save them as Contacts until, something more solid come with probably Cozy V2! who knows ;)

**Comment by Phyks** [comment]
Sorry for the late reply. Is Map meant to stay a fully client side app? I mean, it could most likely use the datastore API to store such markers, isn't it?

Problem with the MaxBox Studio solution is that it relies on a third party, whereas I would have expected Cozy to store all the data within its CouchDB storage.

**Comment by jojorb** [comment]
For now I'm open to several user cases but i deliberately go slow on this topic.
CouchDB storage could be OK with a lot of work to make it useful.

I'd rather go first with a ".json" inside a Map/bookmarks folder from the Cozy-Files.
I think Map should stay as a client side app and go as far as possible like this.

**Comment by Phyks** [comment]
Ok :)
