### ISSUE TITLE
stylesheet leaflet.css 

### ISSUE THREAD

**Issue by jojorb** [RobyRemzy/cozy-map#3]
when trying to link `<link rel='stylesheet' href='../node_modules/dist/leaflet.css' />`  inside index.html.
the map rendered weirdly kind of erratic.  
this problem is solved when the stylesheet is pasted somewhere inside the project. as follow:
  `<link rel='stylesheet' href='styles/leaflet.css' />`  
is my link wrong or are we not allow to link the stylesheet to the node_modules directory?

**Comment by RobyRemzy** [comment]
maybe i've got a lead.
when use require for CSS with:
`require 'leaflet/dist/leaflet.css'`

it can reach the CSS, but with some technical difficulties, like:

```bash
/cozy-map/client/node_modules/leaflet/dist/leaflet.css:3
.leaflet-map-pane,
^
ParseError: Unexpected token
```

it looks like i need `Webpack` to do that!
